-- user_accounts (39 rows)
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM `user_accounts`;
SET FOREIGN_KEY_CHECKS = 1;

INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('james.anderson92', '$2b$12$kpBBGjxrzuLWOefQrSO42uKiv7RyK6txXYPZTQGO', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('connor.hall90', '$2b$12$FpiAMozPf8eGF9IyDN8pbWvTMVTucHYkWCRNYdWC', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('caleb.johnson70', '$2b$12$GBr9BY8DztgjzEPyVcfphV1Za1CdGMEBdqir2EbN', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('isabella.hall51', '$2b$12$5tyM0KFFEIDbugzt32NLqO8JodDGSWxYpJRlBzzm', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('mason.miller20', '$2b$12$jkeaBKsoRRCQ5WMO5AHO4ZektUJrhQR6FEecAtpf', 'admin', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('scarlett.garcia41', '$2b$12$2eY1gOHafUozD13kay5WrRTWPElndTdtdD5GdF0e', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('logan.garcia16', '$2b$12$I4hiCGItUBY3A4Bj1BU0rWEoBSou3ejxjnzuCdZy', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('lucas.hall53', '$2b$12$0IZbcNJOVzNEMr7DXQsedBEmLtST18iwItCqpgrx', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('mia.miller34', '$2b$12$oie0gVZ2cuVixkZVYkBzPoBrUBHtYDZw69CrxG7Y', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('carter.thompson70', '$2b$12$pUlwW1uhw3U3x8EE5GXTeLYHteOtLAQvc1v9r86e', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('caleb.hall20', '$2b$12$zKG5mSoyPstUeC99enq522wjZRL9OaYsP6ihgIqL', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('scarlett.anderson47', '$2b$12$IlPxUkJzZsnWLtBPFX7TOrPMf7otYjc9LVC2JSxy', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('zoey.harris80', '$2b$12$1aSQHqNgAC72qFl41sNLjVHWGaub52Ztd26fEeVV', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('ethan.hall26', '$2b$12$eWwxJLQ6xVJGyOphTExIqqB9r4Eh0C3BfQ0tveH3', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('harper.walker81', '$2b$12$8YMNb5ZqlRtva1JyiNbUnAvwSWJfdjMPqPEBqUhA', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('tyler.taylor27', '$2b$12$cc9hoHyx6RHKT2OZM6rQnBow8w3Ndr86ZfnN8du9', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('emma.thomas63', '$2b$12$HTX3EqEyPXS058H4KPfA1lquCu2r6AZDUd7ne7cb', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('layla.white24', '$2b$12$ChZESFqZ8pIx5F21rWz5FYrsK9EjHvIHCtlRJoWc', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('olivia.davis17', '$2b$12$asnipuaUkxRFZXe1cb51JJRzhbuXMZ5f0pKGytvu', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('lucas.williams89', '$2b$12$QEKoNCP3CrHe69s7QCs90gxwsRbZya1W84UZ3WoX', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('blake.miller94', '$2b$12$Dx7CHHP1QXqE7rs68VRQEDI5SrJH3yvVjc7e5OUn', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('ryan.jones28', '$2b$12$pkjVe6MCIJQ2N9u8tBDNXKveCcwrN8fKxJ7Tc4Jl', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('isabella.thompson34', '$2b$12$YuTOSausPlLNzAuyf8D6axBquKJqwoPCjQ53VQN6', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('nathan.johnson35', '$2b$12$YCsXoblu17rNy8H6h8l7qgATtLFxJpRa5HSUPweP', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('ethan.harris63', '$2b$12$R4UXZVQKWGGw4gZ3mHk0BQSE3BdizIIPtbpaneAR', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('evelyn.white92', '$2b$12$8OA9x14xQPHOvlHGTnabsPHGZpvr6SgYzV2amgcL', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('grace.thompson22', '$2b$12$XhO2I1A3zZyTttp7QDffAUxid7IPz26A4drtgFjD', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('charlotte.garcia69', '$2b$12$Etb6F7nvdE2ODH0A2TVwyJmIeFVr9Qh8yXv6UmFF', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('scarlett.walker41', '$2b$12$Zf2pCLxb0lnXv2Rra6fSEVQOEXfnQsKDGAUuRqph', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('ethan.martin82', '$2b$12$6CpwL7SWktJ5J4x6mKZpRsQXXJcHPeOaAEAw3Cjk', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('emily.thomas44', '$2b$12$RQeNHpCq5QnuVdYXye4JSnE2NiiUHUAKw9iEU1jj', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('sophia.johnson14', '$2b$12$JTfsUkiH8G4ZpZDYUvh7i71S87XwXaHCPPKY6gob', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('chloe.johnson85', '$2b$12$ug0g4ai18eWqMyeuPH7M3EHMoQrof8VRgksbudwA', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('blake.hall79', '$2b$12$UQSyPx3BpdbIKaRdebuFrEHS2JpDzfOvz1dOOdTX', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('sophia.hall40', '$2b$12$pPGNdzSgVaI5z52Dm7tO4fJHS64k2k59yE6752aJ', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('mason.martin77', '$2b$12$L8ZswsRhcds6NUgarDv7p1heEJQjY6fpIzKMWx4s', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('olivia.williams45', '$2b$12$cui8kBRIg6QjcwIAcw58cwQPvI28U5okXkzl5WzP', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('logan.anderson10', '$2b$12$r99HXg1iwWKaqhAhdBwKCnMT4OsNb90AgSB3tjhM', 'archer', '1');
INSERT IGNORE INTO `user_accounts` (`username`, `password_hash`, `role`, `is_active`) VALUES ('ryan.young76', '$2b$12$0rVq4jB6nBvbdFo9xb50OXirZRiRBaepZITGgrsc', 'archer', '1');