-- archers (39 rows)
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM `archers`;
SET FOREIGN_KEY_CHECKS = 1;

INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('1', '2', 'Emily', 'Thomas', '2007-06-27', 'female', 'emily.thomas44');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('2', '9', 'Zoey', 'Harris', '1960-01-28', 'female', 'zoey.harris80');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('3', '4', 'Blake', 'Hall', '1992-02-17', 'male', 'blake.hall79');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('4', '7', 'Scarlett', 'Garcia', '2006-10-11', 'female', 'scarlett.garcia41');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('5', '5', 'Caleb', 'Hall', '2007-07-23', 'male', 'caleb.hall20');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('6', '5', 'Olivia', 'Williams', '1984-10-31', 'female', 'olivia.williams45');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('7', '2', 'Nathan', 'Johnson', '2010-02-11', 'male', 'nathan.johnson35');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('8', '1', 'Scarlett', 'Anderson', '1992-06-13', 'female', 'scarlett.anderson47');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('9', '1', 'Logan', 'Garcia', '1959-10-11', 'male', 'logan.garcia16');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('10', '10', 'Emma', 'Thomas', '1966-11-17', 'female', 'emma.thomas63');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('11', '5', 'Ethan', 'Martin', '2006-04-07', 'male', 'ethan.martin82');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('12', '9', 'Scarlett', 'Walker', '1967-12-22', 'female', 'scarlett.walker41');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('13', '5', 'Mason', 'Martin', '2006-08-07', 'male', 'mason.martin77');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('14', '10', 'Mason', 'Miller', '2010-07-01', 'male', 'mason.miller20');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('15', '3', 'Caleb', 'Johnson', '1981-03-07', 'male', 'caleb.johnson70');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('16', '7', 'Layla', 'White', '2013-02-09', 'female', 'layla.white24');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('17', '10', 'Chloe', 'Johnson', '2007-09-21', 'female', 'chloe.johnson85');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('18', '10', 'Lucas', 'Williams', '2005-11-21', 'male', 'lucas.williams89');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('19', '6', 'Sophia', 'Johnson', '2006-10-22', 'female', 'sophia.johnson14');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('20', '2', 'Tyler', 'Taylor', '2010-04-06', 'male', 'tyler.taylor27');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('21', '6', 'Logan', 'Anderson', '2007-08-04', 'male', 'logan.anderson10');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('22', '9', 'Grace', 'Thompson', '1985-10-27', 'female', 'grace.thompson22');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('23', '10', 'Harper', 'Walker', '2011-10-29', 'female', 'harper.walker81');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('24', '2', 'Olivia', 'Davis', '1992-08-02', 'female', 'olivia.davis17');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('25', '3', 'Ryan', 'Jones', '1998-04-13', 'male', 'ryan.jones28');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('26', '1', 'James', 'Anderson', '1973-09-19', 'male', 'james.anderson92');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('27', '5', 'Mia', 'Miller', '1994-09-29', 'female', 'mia.miller34');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('28', '8', 'Ryan', 'Young', '1972-06-05', 'male', 'ryan.young76');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('29', '4', 'Connor', 'Hall', '2009-05-27', 'male', 'connor.hall90');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('30', '9', 'Carter', 'Thompson', '1992-08-30', 'male', 'carter.thompson70');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('31', '3', 'Ethan', 'Hall', '2010-05-18', 'male', 'ethan.hall26');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('33', '3', 'Lucas', 'Hall', '2005-07-30', 'male', 'lucas.hall53');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('34', '6', 'Charlotte', 'Garcia', '1989-09-14', 'female', 'charlotte.garcia69');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('35', '8', 'Isabella', 'Hall', '1960-03-25', 'female', 'isabella.hall51');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('36', '9', 'Blake', 'Miller', '2005-12-20', 'male', 'blake.miller94');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('37', '5', 'Sophia', 'Hall', '2005-08-08', 'female', 'sophia.hall40');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('38', '4', 'Isabella', 'Thompson', '1962-01-16', 'female', 'isabella.thompson34');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('39', '2', 'Ethan', 'Harris', '1956-11-25', 'male', 'ethan.harris63');
INSERT IGNORE INTO `archers` (`archer_id`, `club_id`, `first_name`, `last_name`, `dob`, `gender`, `username`) VALUES ('40', '4', 'Evelyn', 'White', '2012-03-27', 'female', 'evelyn.white92');